# Generated by Django 3.0.1 on 2020-01-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_genre_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='catalog.Genre'),
        ),
    ]
