# Generated by Django 3.0.1 on 2020-01-24 08:08

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200123_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='', upload_to=catalog.models.user_avatar_path),
            preserve_default=False,
        ),
    ]
